#+TITLE: Of Waves
#+AUTHOR: Jad Saklawi
#+DATE: [2022-05-14 Sat]

#+LaTeX_HEADER: \usepackage{amsthm}
#+LaTeX_HEADER: \usepackage{mdframed}

#+OPTIONS: toc:nil

\newtheorem*{observation}{Observation}
\newmdtheoremenv{observation}{}
\theoremstyle{definition}
\newtheorem{definition}{Definition}[section]

\theoremstyle{example}
\newtheorem{example}{Example}[section]

* Observations

\begin{observation}
Waves are carriers of information, coordinates.
\end{observation}


\begin{observation}
Given a wave burst emitted on an antenna, exactly one wave is read. % \textbf{Date}: \textit{[2018-08-15 Wed]} 
\end{observation}

\begin{observation} \footnotetext{Planet Earth, wave always read by the right antenna for the case of equally distant antennas.} %\textbf{Date}: \textit{[2022-05-14 Sat 11:16]}
Given a wave burst emitted on a multi-polar antenna, wave is read % \textbf{Date}: \textit{[2018-08-15 Wed]} 
   by pole closest to burst. 
\end{observation} 

* Definitions
\begin{definition}{Wave Burst:}
The collection of waves emitted by the same trigger.
\end{definition}
\begin{example}
Consider a click sound. Wave burst would be collection of waves emitted carrying the sound "click".
\end{example}
* Open Problems
  - Number of waves emitted per burst.
  - Direction of waves emitted by a burst.[fn:2]
* Hypotheses
  - Waves are carriers of information, an identifier.
    + Waves emitted by the same burst carry the same identifier.
* Footnotes

[fn:5] For other kinds it is: waves drop waves, of the same type and at same frequency.


[fn:2] For example emitted in a beam, spherical, random, etc..
